# Generated by Django 5.0.7 on 2024-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.IntegerField(default=None),
        ),
    ]
